### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by raresxdd** [Bonfire/ScrapTF-Raffle-Bot#1]
The script is having some errors while i try to run it, it's very confussing, a video tutorial or a detailed explanation will be appreciated.

**Comment by Bonfire** [comment]
Mind pasting the error here? Any information would help me fix any problems and provide a better tutorial.

**Comment by raresxdd** [comment]
When i try to run the script it says:
There's an error in your program: expected an indented block
![image](https://cloud.githubusercontent.com/assets/18448857/14556448/f77c7f94-0300-11e6-9476-aed4a410874e.png)

**Comment by raresxdd** [comment]
![image](https://cloud.githubusercontent.com/assets/18448857/14558142/6cd74c44-0309-11e6-83e3-d0a7cc063e11.png)

**Comment by Bonfire** [comment]
Make sure you're using Python 2.7.6 and that you've successfully installed the Selenium library for Python 2.7.6

**Comment by Bonfire** [comment]
Any updates? May I close this issue?
