### ISSUE TITLE
Error when running it.

### ISSUE THREAD

**Issue by ghost** [Bonfire/ScrapTF-Raffle-Bot#2]
Error 

Traceback (most recent call last):
  File "C:\Users\Adam\Desktop\v\ScrapBot.py", line 72, in <module>
    rafflesNum = (int(rafflesOutOfNums[3] + rafflesOutOfNums[4])) - (int(rafflesOutOfNums[0] + rafflesOutOfNums[1]))
ValueError: invalid literal for int() with base 10: '8/'

**Comment by Bonfire** [comment]
Not going to bother updating this project. In some occurrences (say there are too many or too little raffles currently open) the script will break due to my "hacky" way of pulling information. Apologies.

**Comment by ghost** [comment]
Haha fair enough :P
