### ISSUE TITLE
element paths have updated

### ISSUE THREAD

**Issue by ghost** [Bonfire/ScrapTF-Raffle-Bot#3]
Some of the element locations have updated and changed on the site recently. Breaks script at "rafflesOutOf = driver.find_element_by_xpath('//*[@id="pid-raffles"]/div[3]/div[3]/div[2]/div/i18n/var')" and some other places.

**Comment by Bonfire** [comment]
As I've stated before, I won't be updating this script. If you'd like, you may issue a pull request to fix the script but other than that I won't be touching it. Again, I'd be more than welcome to approve a pull request but I will not be touching the script.
